== 파일 업로드하기
이 가이드는 HTTP multi-part 파일 업로드를 수신할 수 있는 서버 어플리케이션을 만드는 과정을 안내한다.

== 무엇을 만들게 되는가
파일 업로드를 허용하는 Spring Boot 웹 어플리케이션을 만들 것이다. 또한 테스트 파일을 업로드하기 위한 간단한 HTML 인터페이스를 만들 것이다.

== 무엇이 필요한가
* 약 15분
* 선호하는 텍스트 에디터 혹은 IDE
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK 1.8] 혹은 그 이상
* http://www.gradle.org/downloads[Gradle 4+] 혹은 https://maven.apache.org/download.cgi[Maven 3.2+]
* 코드를 IDE로 직접 가져올 수도 있다.
** http://spring.io/guides/gs/sts[Spring Tool Suite (STS)]
** http://spring.io/guides/gs/intellij-idea/[IntelliJ IDEA]

== 이 가이드를 완료하는 방법
대부분의 http://spring.io/guides[Spring Getting Started] 가이드와 마찬가지로, 처음부터 시작하여 각 단계를 완료하거나 이미 익숙한 기본 설정 단계를 건너뛸 수 있다. 어느 쪽이든 코드가 작동한다.

처음부터 시작하려면 <<build-with-gradle>>로 이동하시오.

기본 사항을 건너뛰려면 다음을 수행하라:

* 이 가이드의 소스 저장소를 https://github.com/spring-guides/gs-uploading-files/archive/master.zip[다운로드]하여 압축을 풀거나 http://spring.io/understanding/Git[Git]: `git clone https://github.com/spring-guides/gs-uploading-files.git` 을 사용하여 clone 하시오.
* cd into `gs-uploading-files/initial`
* <<create-a-application-class>>로 넘어가시오.

**끝나면** `gs-uploading-files/complete` 코드와 결과를 비교할 수 있다.

[[build-with-gradle]]
== Gradle로 빌드하기
먼저 기본 빌드 스크립트를 설정한다. Spring으로 app을 만들 때 원하는 빌드 시스템을 사용할 수 있지만 http://gradle.org/[Gradle] 및 https://maven.apache.org/[Maven]으로 작업하는 데 필요한 코드가 여기에 있다. 둘다 익숙하지 않은 경우 http://spring.io/guides/gs/gradle[Gradle로 Java 프로젝트 만들기] 또는 http://spring.io/guides/gs/maven[Maven으로 Java 프로젝트 만들기]를 참조하시오.

=== 디렉토리 구조 만들기
선택한 프로젝트 디렉토리에서 *nix 시스템의 mkdir -p src/main/java/hello를 사용하여 다음 하위 디렉토리 구조를 작성한다:

[source,indent=0]
----
└── src
    └── main
        └── java
            └── hello
----

=== Gradle 빌드 파일 만들기
아래는 https://github.com/spring-guides/gs-uploading-files/blob/master/initial/build.gradle[초기 Gradle 빌드 파일]이다.

`build.gradle`

[source,gradle,indent=0]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.0.5.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

bootJar {
    baseName = 'gs-uploading-files'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-thymeleaf")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}
----

https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html[Spring Boot Gralde 플러그인]은 다음과 같은 여러 편리한 기능을 제공한다:

* 클래스 경로에 있는 모든 jar를 모으고 서비스를 전송하고 실행하는데 좀 더 편하게 만들어주는 실행 가능한 "über-jar"를 빌드한다.
* `public static void main()` 메소드를 검색하여 실행 가능 클래스로 플래그를 지정한다.
* https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml[Spring Boot 의존성]과 일치하도록 버전 번호를 설정하는 빌트인 의존성 리졸버를 제공한다. 모든 버전을 재정의할 수 있지만 기본적으로 Boot에서 선택한 버전으로 설정된다.

== Maven으로 빌드하기
먼저 기본 빌드 스크립트를 설정한다. Spring으로 app을 만들 때 원하는 빌드 시스템을 사용할 수 있지만  https://maven.apache.org/[Maven]으로 작업하는 데 필요한 코드가 여기에 있다. Maven이 익숙하지 않은 경우 http://spring.io/guides/gs/maven[Maven으로 Java 프로젝트 만들기]를 참조하시오.

=== 디렉토리 구조 만들기
선택한 프로젝트 디렉토리에서 *nix 시스템의 mkdir -p src/main/java/hello를 사용하여 다음 하위 디렉토리 구조를 작성한다:

[source,indent=0]
----
└── src
    └── main
        └── java
            └── hello
----

`pom.xml`

[source,xml,indent=0]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework</groupId>
    <artifactId>gs-uploading-files</artifactId>
    <version>0.1.0</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
    </parent>

    <properties>
        <java.version>1.8</java.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
----

https://docs.spring.io/spring-boot/docs/current/maven-plugin[Spring Boot Maven 플러그인]은 다음과 같은 여러 편리한 기능을 제공한다:

* 클래스 경로에 있는 모든 jar를 모으고 서비스를 전송하고 실행하는데 좀 더 편하게 만들어주는 실행 가능한 "über-jar"를 빌드한다.
* `public static void main()` 메소드를 검색하여 실행 가능 클래스로 플래그를 지정한다.
* https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml[Spring Boot 의존성]과 일치하도록 버전 번호를 설정하는 빌트인 의존성 리졸버를 제공한다. 모든 버전을 재정의할 수 있지만 기본적으로 Boot에서 선택한 버전으로 설정된다.

== IDE로 빌드하기
* http://spring.io/guides/gs/sts/[Spring Tool Suite]에서 import 하는 가이드를 읽으시오.
* http://spring.io/guides/gs/intellij-idea[IntelliJ IDEA]에서 가이드를 읽으시오.

[[create-a-application-class]]
== Application 클래스 만들기
Spring Boot MVC 어플리케이션을 시작하려면 먼저 스타터가 필요하다. 여기서는 `spring-boot-starter-thymeleaf` 와 `spring-boot-starter-web` 이 이미 의존성으로 추가되어 있다. 서블릿 컨테이너로 파일을 업로드하려면 `MultipartConfigElement` 클래스를 (web.xml에 `<multipart-config>`) 등록해야 한다. Spring Boot 덕분에 모든 것이 자동으로 구성된다.

이 어플리케이션을 시작하려면 다음 `Application` 클래스만 있으면 된다.

`src/main/java/hello/Application.java`

[source,java,indent=0]
----
package hello;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
----

Spring MVC 자동 구성의 일부로, Spring Boot는 `MultipartConfigElement` 빈을 생성하고 파일을 업로드할 준비를 한다.

== 업로드 컨트롤러 파일 만들기
초기 어플리케이션에는 이미 디스크에 업로드된 파일을 저장하고 로드하는 몇 가지 클래스가 포함되어 있다. 모두 `hello.storage` 패키지에 있다. 우리는 새로운 `FileUploadController` 에서 그것들을 사용할 것이다.

`src/main/java/hello/FileUploadController.java`

[source,java,indent=0]
----
package hello;

import java.io.IOException;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import hello.storage.StorageFileNotFoundException;
import hello.storage.StorageService;

@Controller
public class FileUploadController {

    private final StorageService storageService;

    @Autowired
    public FileUploadController(StorageService storageService) {
        this.storageService = storageService;
    }

    @GetMapping("/")
    public String listUploadedFiles(Model model) throws IOException {

        model.addAttribute("files", storageService.loadAll().map(
                path -> MvcUriComponentsBuilder.fromMethodName(FileUploadController.class,
                        "serveFile", path.getFileName().toString()).build().toString())
                .collect(Collectors.toList()));

        return "uploadForm";
    }

    @GetMapping("/files/{filename:.+}")
    @ResponseBody
    public ResponseEntity<Resource> serveFile(@PathVariable String filename) {

        Resource file = storageService.loadAsResource(filename);
        return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,
                "attachment; filename=\"" + file.getFilename() + "\"").body(file);
    }

    @PostMapping("/")
    public String handleFileUpload(@RequestParam("file") MultipartFile file,
            RedirectAttributes redirectAttributes) {

        storageService.store(file);
        redirectAttributes.addFlashAttribute("message",
                "You successfully uploaded " + file.getOriginalFilename() + "!");

        return "redirect:/";
    }

    @ExceptionHandler(StorageFileNotFoundException.class)
    public ResponseEntity<?> handleStorageFileNotFound(StorageFileNotFoundException exc) {
        return ResponseEntity.notFound().build();
    }

}
----

이 클래스는 `@Controller` 어노테이션이 사용되어 Spring MVC가 이 클래스를 선택하고 경로를 찾는다. 각 메소드에서 `@GetMapping` 또는 `@PostMapping` 태그가 지정되어 경로와 HTTP 액션을 특정 컨트롤러 액션에 연결한다.

이 경우:
* `GET /` 는 `StorageService` 에서 업로드 된 파일의 현재 목록을 찾아서 Thymeleaf 템플릿에 로드한다. `MvcUriComponentsBuilder` 를 사용하여 실제 리소스에 대한 링크를 계산한다.
* `GET /files/{filename}` 은 리소스가 있는 경우 해당 리소스를 로드한 후 `"Content-Disposition"` 응답 헤더를 사용하여 다운로드하기 위해 브라우저로 보낸다.
* `POST /` 는 multi-part 메시지 `file` 을 처리하여 `StorageService` 에 저장하도록 설계되어 있다.

====
프로덕션 시나리오에서는 파일을 임시 위치, 데이터베이스 또는 http://docs.mongodb.org/manual/core/gridfs[Mongo의 GridFS]와 같은 NoSQL 저장소에 저장할 가능성이 높다. 어플리케이션의 파일 시스템을 컨텐츠로 로드하지 않는 것이 가장 좋다.
====

컨트롤러가 스토리지 계층 (예: 파일 시스템)과 상호작용할 수 있도록 `StorageService` 를 제공해야 한다. 인터페이스는 다음과 같다.

`src/main/java/hello/storage/StorageService.java`

[source,java,indent=0]
----
package hello.storage;

import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;

import java.nio.file.Path;
import java.util.stream.Stream;

public interface StorageService {

    void init();

    void store(MultipartFile file);

    Stream<Path> loadAll();

    Path load(String filename);

    Resource loadAsResource(String filename);

    void deleteAll();

}
----

샘플 app에는 인터페이스의 구현 예가 있다. 시간을 절약하고 싶으면 복사해서 붙여넣을 수 있다.

== 간단한 HTML 템플릿 만들기
흥미로운 것을 만들기 위해 다음의 Thymeleaf 템플릿은 파일을 업로드하고 업로드한 내용을 보여주는 좋은 예이다.

`src/main/resources/templates/uploadForm.html`

[source,html,indent=0]
----
<html xmlns:th="http://www.thymeleaf.org">
<body>

	<div th:if="${message}">
		<h2 th:text="${message}"/>
	</div>

	<div>
		<form method="POST" enctype="multipart/form-data" action="/">
			<table>
				<tr><td>File to upload:</td><td><input type="file" name="file" /></td></tr>
				<tr><td></td><td><input type="submit" value="Upload" /></td></tr>
			</table>
		</form>
	</div>

	<div>
		<ul>
			<li th:each="file : ${files}">
				<a th:href="${file}" th:text="${file}" />
			</li>
		</ul>
	</div>

</body>
</html>
----

이 템플릿은 세 부분으로 구성된다:
* Spring MVC가 https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-flash-attributes[flash-scoped 메시지]를 쓰는 선택적인 메시지
* 사용자가 파일을 업로드할 수 있는 양식
* 백앤드에서 제공된 파일 목록

== 파일 업로드 제한 튜닝하기
파일 업로드를 구성할 때 파일 크기에 제한을 설정하는 것이 좋다. 5GB 파일 업로드를 처리하려고 한다고 생각해보라! Spring Boot를 사용하면 자동으로 구성된 `MultipartConfigElement` 를 몇 가지 설정으로 조정할 수 있다.

기존 속성 설정에 다음 속성을 추가하시오:

`src/main/resources/application.properties`

[source,properties,indent=0]
----
spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB
spring.http.multipart.enabled=false
----

multipart 설정은 다음과 같이 제한된다:
* `spring.http.multipart.max-file-size` 가 128KB로 설정되어 총 파일 크기는 128KB를 초과할 수 없다.
* `spring.http.multipart.max-request-size` 가 128KB로 설정되어 있으므로 `multipart/form-data` 에 대한 요청 크기가 128KB를 초과할 수 없다.

== 실행 가능한 어플리케이션 만들기
이 서비스를 외부 어플리케이션 서버에 배포하기 위해 기존의 http://spring.io/understanding/WAR[WAR] 파일로 패키징할 수 있지만, 아래에서 설명하는 더 간단한 접근 방식으로 독립 실행형 어플리케이션을 생성할 수 있다. Java `main()` 메소드로 구동되는 실행 가능한 단일 JAR 파일로 모든 것을 패키징한다. 이 과정에서 외부 인스턴스에 배포하는 대신 HTTP 런타임으로 Spring에서 지원하는 내장형 http://spring.io/understanding/Tomcat[Tomcat] 서블릿 컨테이너를 사용한다.

target 폴더에서 파일을 업로드할 수도 있기 때문에 기본 `Application` 클래스를 향상시키고 시작시 해당 폴더를 삭제하고 다시 만드는 Boot `CommandLineRunner` 를 추가하겠다.

`src/main/java/hello/Application.java`

[source,java,indent=0]
----
package hello;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

import hello.storage.StorageProperties;
import hello.storage.StorageService;

@SpringBootApplication
@EnableConfigurationProperties(StorageProperties.class)
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    CommandLineRunner init(StorageService storageService) {
        return (args) -> {
            storageService.deleteAll();
            storageService.init();
        };
    }
}
----

`@SpringBootApplication` 은 다음을 모두 추가하는 편리한 주석이다:

* `@Configuration` 은 클래스를 어플리케이션 context의 bean 정의 소스로 태그 지정한다.
* `@EnableAutoConfiguration` 은 Spring Boot에게 클래스 경로 설정, 다른 bean 및 다양한 프로퍼티 설정을 기반으로 bean 추가를 시작하도록 한다.
* 일반적으로 `@EnableWebMvc` 를 Spring MVC app에 추가할 것이지만, Spring Boot는 클래스 경로에서 **spring-webmvc**를 발견할 때 그것을 자동으로 추가한다. 이것은 어플리케이션에 웹 어플리케이션으로 플래그를 지정하고 `DispatcherServlet` 설정과 같은 주요 동작을 활성화 한다.
* `@ComponentScan` 은 `hello` 패키지에서 다른 컴포넌트, 구성 및 서비스를 찾아서 컨트롤러를 찾을 수 있도록 Spring에 지시한다. 이 경우에는, 아무것도 없다.

`main()` 메소드는 `Spring Boot의 SpringApplicaiton.run()` 메소드를 사용하여 어플리케이션을 시작한다. 한줄의 XML이 없다는 것을 알고 있었는가? **web.xml** 파일도 없다. 이 웹 어플리케이션은 100% 순수 자바이며 인프라 구성에 대해 다룰 필요가 없다.

=== 실행 가능한 JAR 만들기
Gradle 또는 Maven을 사용하여 커맨드 라인에서 어플리케이션을 실행할 수 있다. 또는 모든 필요한 의존성, 클래스 및 리소스 포함하는 단일 실행 가능한 JAR 파일을 빌드하고 실행할 수 있다. 따라서 개발 생명주기(life cycle), 다양한 환경에 걸쳐 어플리케이션으로 서비스를 쉽게 제공 및 배포할 수 있다.

Gradle을 사용하는 경우 `./gradlew bootRun` 을 사용하여 어플리케이션을 실행할 수 있다. 또는 `./gradlew build` 를 사용하여 JAR 파일을 작성할 수 있다. 그런 다음 JAR 파일을 실행할 수 있다:

[source,bash,indent=0]
----
java -jar build/libs/gs-uploading-files-0.1.0.jar
----

Maven을 사용하는 경우 ./mvnw spring-boot:run을 사용하여 어플리케이션을 실행할 수 있다. 또는 ./mvnw clean package로 JAR 파일을 빌드할 수 있다. 그런 다음 JAR 파일을 실행할 수 있다:

[source,bash,indent=0]
----
java -jar target/gs-uploading-files-0.1.0.jar
----

====
위 절차는 실행 가능한 JAR를 생성한다. 고전의 http://spring.io/guides/gs/convert-jar-to-war/[WAR 파일을 빌드]하도록 선택할 수도 있다.
====

파일 업로드를 수신하는 서버 부분을 실행한다. 로깅 출력이 표시된다. 서비스가 몇 초 내에 가동되고 실행될 것이다.

업로드 폼을 보기 위해 서버가 실행 중인 상태에서 브라우저를 열고 http://localhost:8080/ 을 접속하시오. (작은) 파일을 선택하고 "Upload"를 누르면 컨트롤러로 부터 성공 페이지가 표시된다. 너무 큰 파일을 선택하면 오류 페이지가 표시된다.

브라우저 창에 다음과 같은 항목이 표시된다:

[source,indent=0]
----
You successfully uploaded <name of your file>!
----

== 어플리케이션 테스트하기
어플리케이션에서 특정 기능을 테스트하는 방법은 여러 가지가 있다. 다음은 Servlet 컨테이너를 시작할 필요 없는 `MockMvc` 를 활용하는 예제이다.

`src/test/java/hello/FileUploadTests.java`

[source,java,indent=0]
----
package hello;

import java.nio.file.Paths;
import java.util.stream.Stream;

import org.hamcrest.Matchers;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.then;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.fileUpload;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.model;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import hello.storage.StorageFileNotFoundException;
import hello.storage.StorageService;

@RunWith(SpringRunner.class)
@AutoConfigureMockMvc
@SpringBootTest
public class FileUploadTests {

    @Autowired
    private MockMvc mvc;

    @MockBean
    private StorageService storageService;

    @Test
    public void shouldListAllFiles() throws Exception {
        given(this.storageService.loadAll())
                .willReturn(Stream.of(Paths.get("first.txt"), Paths.get("second.txt")));

        this.mvc.perform(get("/")).andExpect(status().isOk())
                .andExpect(model().attribute("files",
                        Matchers.contains("http://localhost/files/first.txt",
                                "http://localhost/files/second.txt")));
    }

    @Test
    public void shouldSaveUploadedFile() throws Exception {
        MockMultipartFile multipartFile = new MockMultipartFile("file", "test.txt",
                "text/plain", "Spring Framework".getBytes());
        this.mvc.perform(fileUpload("/").file(multipartFile))
                .andExpect(status().isFound())
                .andExpect(header().string("Location", "/"));

        then(this.storageService).should().store(multipartFile);
    }

    @SuppressWarnings("unchecked")
    @Test
    public void should404WhenMissingFile() throws Exception {
        given(this.storageService.loadAsResource("test.txt"))
                .willThrow(StorageFileNotFoundException.class);

        this.mvc.perform(get("/files/test.txt")).andExpect(status().isNotFound());
    }

}
----

이 테스트에서는 Controller와 `StorageService` 와의 상호 작용을 설정하기 위해 다양한 mock을 사용하고 있지만 `MockMultipartFile` 을 사용하여 Servlet 컨테이너 자체와도 상호 작용을 설정한다.

통합 테스트의 예는 `FileUploadIntegratedTests` 클래스를 참조하시오.

== 요약
축하합니다! Spring을 사용하여 파일 업로드를 처리하는 웹 어플리케이션을 개발했다.

== 다른 예제들
다음 가이드들도 도움이 될 것이다:

* https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC]
* https://spring.io/guides/gs/handling-form-submission/[Handling Form Submission]
* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]