== RESTful 웹 서비스 사용하기
이 가이드는 RESTful 웹 서비스를 사용하는 어플리케이션을 만드는 과정을 안내한다.

== 무엇을 만들게 되는가
http://gturnquist-quoters.cfapps.io/api/random에서 Spring의 `RestTemplate` 를 사용하여 랜덤의 Spring Boot 인용문을 검색하는 어플리케이션을 만들 것이다.

== 무엇이 필요한가
* 약 15분
* 선호하는 텍스트 에디터 혹은 IDE
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK 1.8] 혹은 그 이상
* http://www.gradle.org/downloads[Gradle 4+] 혹은 https://maven.apache.org/download.cgi[Maven 3.2+]
* 코드를 IDE로 직접 가져올 수도 있다.
** http://spring.io/guides/gs/sts[Spring Tool Suite (STS)]
** http://spring.io/guides/gs/intellij-idea/[IntelliJ IDEA]

== 이 가이드를 완료하는 방법
대부분의 http://spring.io/guides[Spring Getting Started] 가이드와 마찬가지로, 처음부터 시작하여 각 단계를 완료하거나 이미 익숙한 기본 설정 단계를 건너뛸 수 있다. 어느 쪽이든 코드가 작동한다.

처음부터 시작하려면 <<build-with-gradle>>로 이동하시오.

기본 사항을 건너뛰려면 다음을 수행하라:

* 이 가이드의 소스 저장소를 https://github.com/spring-guides/gs-consuming-rest/archive/master.zip[다운로드]하여 압축을 풀거나 http://spring.io/understanding/Git[Git]: `git clone https://github.com/spring-guides/gs-consuming-rest.git` 을 사용하여 clone 하시오.
* cd into `gs-consuming-rest/initial`
* <<fetch-a-rest-source>>로 넘어가시오.

**끝나면** `gs-consuming-rest/complete` 코드와 결과를 비교할 수 있다.

[[build-with-gradle]]
== Gradle로 빌드하기
먼저 기본 빌드 스크립트를 설정한다. Spring으로 app을 만들 때 원하는 빌드 시스템을 사용할 수 있지만 http://gradle.org/[Gradle] 및 https://maven.apache.org/[Maven]으로 작업하는 데 필요한 코드가 여기에 있다. 둘다 익숙하지 않은 경우 http://spring.io/guides/gs/gradle[Gradle로 Java 프로젝트 만들기] 또는 http://spring.io/guides/gs/maven[Maven으로 Java 프로젝트 만들기]를 참조하시오.

=== 디렉토리 구조 만들기
선택한 프로젝트 디렉토리에서 *nix 시스템의 mkdir -p src/main/java/hello를 사용하여 다음 하위 디렉토리 구조를 작성한다:

[source,indent=0]
----
└── src
    └── main
        └── java
            └── hello
----

=== Gradle 빌드 파일 만들기
아래는 https://github.com/spring-guides/gs-consuming-rest/blob/master/initial/build.gradle[초기 Gradle 빌드 파일]이다.

`build.gradle`

[source,gradle,indent=0]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.0.5.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

bootJar {
    baseName = 'gs-consuming-rest'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile("org.springframework.boot:spring-boot-starter")
    compile("org.springframework:spring-web")
    compile("com.fasterxml.jackson.core:jackson-databind")
    testCompile("junit:junit")
}
----

https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html[Spring Boot Gralde 플러그인]은 다음과 같은 여러 편리한 기능을 제공한다:

* 클래스 경로에 있는 모든 jar를 모으고 서비스를 전송하고 실행하는데 좀 더 편하게 만들어주는 실행 가능한 "über-jar"를 빌드한다.
* `public static void main()` 메소드를 검색하여 실행 가능 클래스로 플래그를 지정한다.
* https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml[Spring Boot 의존성]과 일치하도록 버전 번호를 설정하는 빌트인 의존성 리졸버를 제공한다. 모든 버전을 재정의할 수 있지만 기본적으로 Boot에서 선택한 버전으로 설정된다.

== Maven으로 빌드하기
먼저 기본 빌드 스크립트를 설정한다. Spring으로 app을 만들 때 원하는 빌드 시스템을 사용할 수 있지만  https://maven.apache.org/[Maven]으로 작업하는 데 필요한 코드가 여기에 있다. Maven이 익숙하지 않은 경우 http://spring.io/guides/gs/maven[Maven으로 Java 프로젝트 만들기]를 참조하시오.

=== 디렉토리 구조 만들기
선택한 프로젝트 디렉토리에서 *nix 시스템의 mkdir -p src/main/java/hello를 사용하여 다음 하위 디렉토리 구조를 작성한다:

[source,indent=0]
----
└── src
    └── main
        └── java
            └── hello
----

`pom.xml`

[source,xml,indent=0]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework</groupId>
    <artifactId>gs-consuming-rest</artifactId>
    <version>0.1.0</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
    </parent>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
----

https://docs.spring.io/spring-boot/docs/current/maven-plugin[Spring Boot Maven 플러그인]은 다음과 같은 여러 편리한 기능을 제공한다:

* 클래스 경로에 있는 모든 jar를 모으고 서비스를 전송하고 실행하는데 좀 더 편하게 만들어주는 실행 가능한 "über-jar"를 빌드한다.
* `public static void main()` 메소드를 검색하여 실행 가능 클래스로 플래그를 지정한다.
* https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml[Spring Boot 의존성]과 일치하도록 버전 번호를 설정하는 빌트인 의존성 리졸버를 제공한다. 모든 버전을 재정의할 수 있지만 기본적으로 Boot에서 선택한 버전으로 설정된다.

== IDE로 빌드하기
* http://spring.io/guides/gs/sts/[Spring Tool Suite]에서 import 하는 가이드를 읽으시오.
* http://spring.io/guides/gs/intellij-idea[IntelliJ IDEA]에서 가이드를 읽으시오.

[[fetch-a-rest-resource]]
== REST 리소스 가져오기
프로젝트 설정이 완료되면 RESTful 서비스를 사용하는 간단한 어플리케이션을 만들 수 있다.

RESTful 서비스가 http://gturnquist-quoters.cfapps.io/api/random에서 동작되고 있다. Spring Boot에 대한 인용문을 랜덤으로 가져와서 JSON 문서로 반환한다.

웹 브라우저나 curl을 통해 URL을 요청하면 다음과 같은 JSON 문서를 받게될 것이다.

[source,json,indent=0]
----
{
   type: "success",
   value: {
      id: 10,
      quote: "Really loving Spring Boot, makes stand alone Spring apps easy."
   }
}
----

많이 간단하지만, 브라우저나 curl을 통해 가져올 때 유용하지는 않다.

더 유용하게 사용하는 방법은 REST 웹 서비스를 프로그래밍 방식으로 사용하는 것이다. 이 작업을 돕기 위해 Spring은 https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html[`RestTemplate`] 이라는 편리한 템플릿 클래스를 제공한다. `RestTemplate` 은 대부분의 RESTful 서비스와 상호작용을 한줄로 표현한다. 그리고 데이터를 커스텀 도메인 타입에 바인딩할 수도 있다.

먼저 필요한 데이터를 포함할 도메인 클래스를 만든다.

`src/main/java/hello/Quote.java`

[source,java,indent=0]
----
package hello;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Quote {

    private String type;
    private Value value;

    public Quote() {
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Value getValue() {
        return value;
    }

    public void setValue(Value value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "Quote{" +
                "type='" + type + '\'' +
                ", value=" + value +
                '}';
    }
}
----

보다시피, 이 클래스는 몇 가지 속성과 getter 메소드가 있는 간단한 Java 클래스이다. Jackson JSON 처리 라이브러리의 `@JsonIgnoreProperties` 어노테이션이 달려 있어 이 유형에 바인딩되지 않은 모든 속성을 무시하는 것을 나타낸다.

위에서 작성한 커스텀 타입에 데이터를 직접 바인딩하려면 API에서 반환 된 JSON 문서의 key와 완전히 동일한 변수 이름을 지정해야 한다. JSON 문서의 변수 이름과 key가 일치하지 않는 경우 `@JsonProperty` 어노테이션을 사용하여 JSON 문서의 정확한 key를 지정해야 한다.

내부 인용문 자체를 포함하려면 추가 클래스가 필요하다.

`src/main/java/hello/Value.java`

[source,java,indent=0]
----
package hello;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Value {

    private Long id;
    private String quote;

    public Value() {
    }

    public Long getId() {
        return this.id;
    }

    public String getQuote() {
        return this.quote;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setQuote(String quote) {
        this.quote = quote;
    }

    @Override
    public String toString() {
        return "Value{" +
                "id=" + id +
                ", quote='" + quote + '\'' +
                '}';
    }
}
----

이는 동일한 어노테이션을 사용하지만 다른 데이터 필드에 매핑된다.

== 실행 가능한 어플리케이션 만들기
이 서비스를 외부 어플리케이션 서버에 배포하기 위해 기존의 http://spring.io/understanding/WAR[WAR] 파일로 패키징할 수 있지만, 아래에서 설명하는 더 간단한 접근 방식으로 독립 실행형 어플리케이션을 생성할 수 있다. Java `main()` 메소드로 구동되는 실행 가능한 단일 JAR 파일로 모든 것을 패키징한다. 이 과정에서 외부 인스턴스에 배포하는 대신 HTTP 런타임으로 Spring에서 지원하는 내장형 http://spring.io/understanding/Tomcat[Tomcat] 서블릿 컨테이너를 사용한다.

이제 `RestTemplate` 을 사용하는 `Application` 클래스를 작성하여 Spring Boot 인용문 서비스에서 데이터를 가져올 수 있다.

`src/main/java/hello/Application.java`

[source,java,indent=0]
----
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.client.RestTemplate;

public class Application {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    public static void main(String args[]) {
        RestTemplate restTemplate = new RestTemplate();
        Quote quote = restTemplate.getForObject("http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
        log.info(quote.toString());
    }

}
----

Jackson JSON 처리 라이브러리가 클래스 경로에 있기 때문에 `RestTemplate` 은 https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/converter/HttpMessageConverter.html[메시지 컨버터]를 통해 수신한 JSON 데이터를 `Quote` 객체로 변환한다. 여기에서 `Quote` 객체의 내용이 콘솔에 기록된다.

여기서는 `RestTemplate` 을 사용하여 HTTP `GET` 요청만 했다. 그러나 RestTemplate은 `POST`, `PUT` 및 `DELETE` 와 같은 다른 HTTP도 지원한다.

== Spring Boot로 어플리케이션 Lifecycle 관리하기
지금까지 어플리케이션에서 Spring Boot를 사용하지 않았다. 하지만 Spring Boot를 이용하면 몇 가지 장점이 있고, 사용하는 것도 어렵지 않다. 장점 중 하나는 Spring Boot가 `RestTemplate` 에서 메시지 컨버터를 관리하도록 하여 사용자 정의를 선언적으로 쉽게 추가할 수 있도록 한다. 이를 위해 main 클래스에 `@SpringBootApplication` 을 사용하고 Spring Boot 어플리케이션과 마찬가지로 main 메소드를 시작하도록 변환한다. 마지막으로 `RestTemplate` 을 `CommandLineRunner` 콜백으로 이동한다. 그러면 시작시 Spring Boot에 의해 실행된다:

`src/main/java/hello/Application.java`

[source,java,indent=0]
----
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class Application {

	private static final Logger log = LoggerFactory.getLogger(Application.class);

	public static void main(String args[]) {
		SpringApplication.run(Application.class);
	}

	@Bean
	public RestTemplate restTemplate(RestTemplateBuilder builder) {
		return builder.build();
	}

	@Bean
	public CommandLineRunner run(RestTemplate restTemplate) throws Exception {
		return args -> {
			Quote quote = restTemplate.getForObject(
					"http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
			log.info(quote.toString());
		};
	}
}
----

`RestTemplateBuilder` 는 Spring에 의해 주입되며, `RestTemplate` 을 생성하기 위해 이 템플릿을 사용하면 Spring Boot에서 메시지 컨버터와 request factories로 발생하는 모든 자동 구성을 활용할 수 있다. 또한 `RestTemplate` 을 `@Bean` 으로 추출하여 쉽게 테스트할 수 있다.

=== 실행 가능한 JAR 만들기
Gradle 또는 Maven을 사용하여 커맨드 라인에서 어플리케이션을 실행할 수 있다. 또는 모든 필요한 의존성, 클래스 및 리소스 포함하는 단일 실행 가능한 JAR 파일을 빌드하고 실행할 수 있다. 따라서 개발 생명주기(life cycle), 다양한 환경에 걸쳐 어플리케이션으로 서비스를 쉽게 제공 및 배포할 수 있다.

Gradle을 사용하는 경우 `./gradlew bootRun` 을 사용하여 어플리케이션을 실행할 수 있다. 또는 `./gradlew build` 를 사용하여 JAR 파일을 작성할 수 있다. 그런 다음 JAR 파일을 실행할 수 있다:

[source,bash,indent=0]
----
java -jar build/libs/gs-consuming-rest-0.1.0.jar
----

Maven을 사용하는 경우 ./mvnw spring-boot:run을 사용하여 어플리케이션을 실행할 수 있다. 또는 ./mvnw clean package로 JAR 파일을 빌드할 수 있다. 그런 다음 JAR 파일을 실행할 수 있다:

[source,bash,indent=0]
----
java -jar target/gs-consuming-rest-0.1.0.jar
----

====
위 절차는 실행 가능한 JAR를 생성한다. 고전의 http://spring.io/guides/gs/convert-jar-to-war/[WAR 파일을 빌드]하도록 선택할 수도 있다.
====

다음과 같이 랜덤의 인용문이 출력되는 것을 볼 수 있다:

[source,indent=0]
----
2015-09-23 14:22:26.415  INFO 23613 --- [main] hello.Application  : Quote{type='success', value=Value{id=12, quote='@springboot with @springframework is pure productivity! Who said in #java one has to write double the code than in other langs? #newFavLib'}}
----

====
만약 `Could not extract response: no suitable HttpMessageConverter found for response type [class hello.Quote]` 오류가 발생하면 백엔드 서비스에 연결할 수 없는 환경일 가능성이 있다 (만약 연결된 경우 JSON을 보낸다). proxy를 사용중이면 표준 시스템 프로퍼티 http.proxyHost 및 http.proxyPort를 환경에 적절한 값으로 설정하시오.
====

== 요약
축하합니다! Spring을 사용하여 간다한 REST 클라이언트를 개발했다.

== 다른 예제들
다음 가이드들도 도움이 될 것이다:

* https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]
* https://spring.io/guides/gs/consuming-rest-angularjs/[Consuming a RESTful Web Service with AngularJS]
* https://spring.io/guides/gs/consuming-rest-jquery/[Consuming a RESTful Web Service with jQuery]
* https://spring.io/guides/gs/consuming-rest-restjs/[Consuming a RESTful Web Service with rest.js]
* https://spring.io/guides/gs/accessing-gemfire-data-rest/[Accessing GemFire Data with REST]
* https://spring.io/guides/gs/accessing-mongodb-data-rest/[Accessing MongoDB Data with REST]
* https://spring.io/guides/gs/accessing-data-mysql/[Accessing data with MySQL]
* https://spring.io/guides/gs/accessing-data-rest/[Accessing JPA Data with REST]
* https://spring.io/guides/gs/accessing-neo4j-data-rest/[Accessing Neo4j Data with REST]
* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]
* https://spring.io/guides/gs/testing-restdocs/[Creating API Documentation with Restdocs]
* https://spring.io/guides/gs/rest-service-cors/[Enabling Cross Origin Requests for a RESTful Web Service]
* https://spring.io/guides/gs/rest-hateoas/[Building a Hypermedia-Driven RESTful Web Service]